server:
  port: 8080

tolerance:
  fixed: 7               # Tolerância fixa em km/h (até 100 km/h)
  percent: 7             # Tolerância percentual (acima de 100 km/h)
  limitForPercent: 100   # Limite que define quando usar tolerância percentual

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC      

logging:
  level:
    root: INFO
    com.mulato.api.speedviolation: DEBUG

